dataset: "FashionMNIST"
channels: 1
image_size: 28
patch_size: 4
num_classes: 10

depth: 8
emb_size: 512
head_num: 8
batch_size: 256
n_epochs: 300
warmup_epochs: 10
betas: '0.9,0.99'
mixup: true
longtail: true
imb_type: 'exp'
imb_factor: 0.05

lr: 1e-4
