image_size: 224
dataset: 'ImageNet'
depth: 8
emb_size: 512
head_num: 8
batch_size: 384
n_epochs: 300
warmup_epochs: 10
patch_size: 16
betas: '0.9,0.99'
mixup: true
longtail: true
imb_factor: 0.05
lr: 1e-4
