model_name: SwT
dataset: CIFAR10
num_classes: 10
channels: 3
image_size: 32
patch_size: 2
window_size: 2

emb_size: 48
depth: 8
head_num: 3

batch_size: 256
n_epochs: 200
warmup_epochs: 10
betas: '0.9,0.99'
lr: 3e-4
weight_decay: 0.05
drop_p: 0.1
label_smoothing: 0.1

mixup: true
longtail: true
imb_type: exp
imb_factor: 0.01
loss_type: LDAM

head_class_idx: [0, 3]
med_class_idx:  [3, 7]
tail_class_idx: [7, 10]
